# This file created by conda-build 3.18.2
# ------------------------------------------------

package:
    name: gstreamer
    version: 1.14.5
source:
    -   sha256: e40888752883177e97b2d90cd68591f87ccd213dc0178ff721d80a4cdaad34b5
        url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.14.5.tar.xz
    -   folder: plugins_base
        sha256: 7bfa9b329ea7f3c654fa1b2d43650bf2646598a5e3cb21f42c516b7e975d638e
        url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.14.5.tar.xz
build:
    activate_in_script: true
    number: 0
    run_exports:
        - gstreamer >=1.14.5,<1.15.0a0
    string: h36ae1b5_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - bison 3.4 he1b5a44_0
        - flex 2.6.4 hf484d3e_1004
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - cairo 1.16.0 ha4e643d_1000
        - fontconfig 2.13.1 he4413a7_1000
        - freetype 2.10.0 he983fc9_0
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 hf63aee3_1001
        - gobject-introspection 1.58.2 py37h2da5eee_1000
        - icu 58.2 hf484d3e_1000
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 h13577e0_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pcre 8.41 hf484d3e_1003
        - pixman 0.34.0 h14c3975_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 hed695b0_1002
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.9 h516909a_1004
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.7 h14c3975_1000
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - glib >=2.58.3,<3.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=7.3.0
        - pcre >=8.41,<9.0a0
        - xz >=5.2.4,<5.3.0a0
test:
    commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
about:
    doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/docs
    summary: Library for constructing graphs of media-handling components
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - msarahan
