CI: azure
blas_default_impl: openblas
blas_impl: openblas
blas_impl_lib: libopenblas.so.0
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fortran_compiler: gfortran
fortran_compiler_version: '7'
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - blas_impl
  - blas_impl_lib
