# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 13 01:05:56 2019
# ------------------------------------------------

package:
    name: glib
    version: 2.58.3
source:
    patches:
        - hardcoded-paths.patch
        - meson-rpaths.patch
        - skip-some-tests.patch
    sha256: 8f43c31767e88a25da72b52a40f3301fefc49a665b56dc10ee7cc9565cbe7481
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.58/glib-2.58.3.tar.xz
build:
    number: '1002'
    run_exports:
        - glib >=2.58.3,<3.0a0
    string: h6f030ca_1002
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ninja 1.9.0 h6bb024c_0
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - gettext 0.19.8.1 hc5be6a0_1002
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - meson 0.51.1 py_0
        - ncurses 6.1 hf484d3e_1002
        - ninja 1.9.0 h6bb024c_0
        - openssl 1.1.1c h516909a_0
        - pcre 8.41 hf484d3e_1003
        - python 3.6.7 h357f687_1005
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - gettext >=0.19.8.1,<1.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=7.3.0
        - libiconv >=1.15,<1.16.0a0
        - libiconv >=1.15,<1.16.0a0
        - libstdcxx-ng >=7.3.0
        - pcre >=8.41,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.so
        - test ! -f ${PREFIX}/lib/libgobject-2.0.la
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - gapplication help
        - gdbus help
        - gio version
        - gio-querymodules .
        - glib-compile-resources --help
        - glib-compile-schemas --help
        - gobject-query --help
        - gresource help
        - gtester --help
about:
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1
    license_file: COPYING
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
        - scopatz
