# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 24 14:13:10 2019
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.9
source:
    patches:
        - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
        - 0004-CVE-2017-8872.patch
    sha256: 94fb70890143e3c6549f265cee93ec064c80a84c42ad0f23e85ee1fd6540a871
    url: http://xmlsoft.org/sources/libxml2-2.9.9.tar.gz
build:
    number: '5'
    run_exports:
        - libxml2 >=2.9.9,<2.10.0a0
    string: hee79883_5
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - _libgcc_mutex 0.1 main
        - icu 64.2 he1b5a44_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - icu >=64.2,<65.0a0
        - icu >=64.2,<65.0a0
        - libgcc-ng >=7.3.0
        - libiconv >=1.15,<1.16.0a0
        - libiconv >=1.15,<1.16.0a0
        - xz >=5.2.4,<5.3.0a0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - jakirkham
        - jschueller
        - msarahan
        - ocefpaf
        - scopatz
