# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 17 03:03:51 2019
# ------------------------------------------------

package:
    name: scipy
    version: 1.3.1
source:
    patches:
        - gh10591.patch
    sha256: 4ea68de2840cf7d35c58464412d21f6f154cab7fba610c11002603ee0b9e2372
    url: https://github.com/scipy/scipy/archive/v1.3.1.tar.gz
build:
    number: '2'
    string: py36h921218d_2
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py36_1
        - cython 0.29.13 py36he1b5a44_0
        - libblas 3.8.0 6_h6e990d7_netlib
        - libcblas 3.8.0 6_h6e990d7_netlib
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - liblapack 3.8.0 6_h6e990d7_netlib
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - numpy 1.14.6 py36he5ce36f_1201
        - openssl 1.1.1c h516909a_0
        - pip 19.2.2 py36_0
        - python 3.6.7 h357f687_1005
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py36_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py36_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - libblas >=3.8.0,<4.0a0
        - libcblas >=3.8.0,<4.0a0
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - liblapack >=3.8.0,<3.9.0a0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.14.6,<2.0a0
        - python >=3.6,<3.7.0a0
test:
    requires:
        - mpmath
        - pytest
about:
    description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

        science, and engineering.

        '
    dev_url: https://github.com/scipy/scipy
    doc_url: http://www.scipy.org/docs.html
    home: http://www.scipy.org/
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Scientific Library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - beckermr
        - jakirkham
        - msarahan
        - ocefpaf
        - rgommers
