# This file created by conda-build 3.18.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jun 16 15:15:17 2019
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2019.6.16
source:
    sha256: 945e3ba63a0b9f577b1395204e13c3a231f9bc0223888be653286534e5873695
    url: https://pypi.io/packages/source/c/certifi/certifi-2019.6.16.tar.gz
build:
    number: '0'
    string: hecc5488_0
test:
    commands:
        - test -f "${PREFIX}/ssl/cacert.pem"
        - test -f "${PREFIX}/ssl/cert.pem"
        - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
    requires:
        - curl
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    license_file: LICENSE
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
