# This file created by conda-build 3.17.8
# ------------------------------------------------

package:
    name: matplotlib
    version: 3.1.1
source:
    sha256: 29d1a239bb7d1095d98d8831bb661519ab0d23e30d38ed47729f554f15e8cd3e
    url: https://github.com/matplotlib/matplotlib/archive/v3.1.1.tar.gz
build:
    noarch: false
    number: '1'
    string: py36_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - python 3.6.7 h357f687_1005
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - matplotlib-base 3.1.1 py36he7580a8_1
        - pyqt
        - python >=3.6,<3.7.0a0
test:
    imports:
        - matplotlib
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
